// The field manual (manual*.html, generated by gen_manual.py): no sideways scroll at any test width,
// one h1, the sub-page HUD with a rung per panel, every in-manual link lands on a real id, and the
// COPY control puts a block's exact text on the clipboard. Screenshots go to tests/out/.
const fs = require('fs'), path = require('path');
const { launch, check, SITE } = require('./cdp');
const PAGES = fs.readdirSync(SITE).filter(f => /^manual(-\d+)?\.html$/.test(f)).sort();
const SIZES = [[375, 740], [768, 1024], [1366, 600], [1920, 1080]];
(async () => {
  check('manual pages exist', PAGES.length === 7, PAGES.join(','));
  const p = await launch({ width: 1440, height: 900 });
  const ids = {};
  for (const pg of PAGES) {
    for (const [w, h] of SIZES) {
      await p.size(w, h); await p.goto(pg, 700);
      check(`${pg} @${w} no h-overflow`, await p.eval('document.documentElement.scrollWidth <= innerWidth'));
      await p.shot(path.join(__dirname, `out/${pg.replace('.html', '')}-${w}.png`), false);
    }
    await p.size(1440, 900); await p.goto(pg, 700);
    check(`${pg} has one h1`, await p.eval("document.querySelectorAll('h1').length === 1"));
    check(`${pg} body.page`, await p.eval("document.body.classList.contains('page')"));
    check(`${pg} lang="en"`, await p.eval("document.documentElement.lang === 'en'"));
    check(`${pg} nav marks current page`, await p.eval(`!!document.querySelector('.strip a[aria-current="page"][href="${pg}"]')`));
    check(`${pg} HUD has a rung per panel`, await p.eval("document.querySelectorAll('.phud-ladder li').length === document.querySelectorAll('.screen .panel').length"));
    check(`${pg} scope reads FIELD MANUAL`, /FIELD MANUAL/.test(await p.eval("document.querySelector('.phud-status').textContent")));
    const dups = await p.eval("(()=>{const s=new Set(),d=new Set();document.querySelectorAll('[id]').forEach(e=>s.has(e.id)?d.add(e.id):s.add(e.id));return [...d].join(',')})()");
    check(`${pg} no duplicate ids`, dups === '', dups);
    ids[pg] = await p.eval("[...document.querySelectorAll('[id]')].map(e => e.id)");
    const nCode = await p.eval("document.querySelectorAll('.fm-code').length");
    if (nCode) {
      check(`${pg} every code block has a COPY control`, await p.eval("[...document.querySelectorAll('.fm-code')].every(b => b.querySelector('button.copy'))"));
      // the clipboard itself needs a user gesture in headless Chrome, so catch what would go on it
      await p.eval("window.__copied = null; navigator.clipboard.writeText = t => { window.__copied = t; return Promise.resolve(); }; true");
      await p.eval("document.querySelector('.fm-code button.copy').click(); true"); await p.sleep(100);
      check(`${pg} COPY copies the block's exact text`, await p.eval("window.__copied === document.querySelector('.fm-code pre code').textContent"));
      check(`${pg} COPY confirms`, await p.eval("document.querySelector('.fm-code button.copy').textContent") === 'COPIED');
    }
  }
  // every link inside the manual lands on a page that exists and, with a #fragment, on a real id
  const bad = [];
  for (const pg of PAGES) {
    await p.goto(pg, 400);
    const hrefs = await p.eval("[...document.querySelectorAll('.screen a[href], .strip a[href]')].map(a => a.getAttribute('href')).filter(h => !/^(https?:|mailto:)/.test(h))");
    for (const h of hrefs) {
      const [file, frag] = h.split('#'), target = file || pg;
      if (!fs.existsSync(path.join(SITE, target))) { bad.push(pg + ' -> ' + h); continue; }
      if (frag && ids[target] && !ids[target].includes(frag)) bad.push(pg + ' -> ' + h);
    }
  }
  check('manual links all resolve', bad.length === 0, bad.slice(0, 8).join(' | '));
  await p.goto('hangar.html', 900);
  check('hangar links the field manual', await p.eval("!!document.querySelector('a[href=\"manual.html\"]')"));
  check('no JS errors on manual pages', p.errors.length === 0, p.errors.join(' | '));
  p.close();
})();
