// The field manual (manual*.html, generated by gen_manual.py): no sideways scroll at any test width,
// one h1, the sub-page HUD with a rung per panel, every in-manual link lands on a real id, and the
// COPY control puts a block's exact text on the clipboard. Screenshots go to tests/out/.
const fs = require('fs'), path = require('path');
const { launch, check, SITE } = require('./cdp');
// the library, and every manual's pages (manual-<slug>[-n].html); the old manual-<n>.html are redirect stubs
const PAGES = fs.readdirSync(SITE).filter(f => /^manual(-[a-z][a-z0-9-]*(-\d+)?)?\.html$/.test(f)).sort();
const SOURCES = fs.readdirSync(path.join(SITE, 'docs/manuals')).filter(f => f.endsWith('.md')).map(f => f.slice(0, -3));
const SIZES = [[375, 740], [768, 1024], [1366, 600], [1920, 1080]];
(async () => {
  check('library and manual pages exist', PAGES.includes('manual.html') && SOURCES.every(s => PAGES.includes(`manual-${s}.html`)), PAGES.join(','));
  const p = await launch({ width: 1440, height: 900 });
  const ids = {};
  for (const pg of PAGES) {
    for (const [w, h] of SIZES) {
      await p.size(w, h); await p.goto(pg, 700);
      check(`${pg} @${w} no h-overflow`, await p.eval('document.documentElement.scrollWidth <= innerWidth'));
      await p.shot(path.join(__dirname, `out/${pg.replace('.html', '')}-${w}.png`), false);
    }
    await p.size(1440, 900); await p.goto(pg, 700);
    check(`${pg} has one h1`, await p.eval("document.querySelectorAll('h1').length === 1"));
    check(`${pg} body.page`, await p.eval("document.body.classList.contains('page')"));
    check(`${pg} lang="en"`, await p.eval("document.documentElement.lang === 'en'"));
    check(`${pg} nav marks current page`, await p.eval(`!!document.querySelector('.strip a[aria-current="page"][href="${pg}"]')`));
    check(`${pg} HUD has a rung per panel`, await p.eval("document.querySelectorAll('.phud-ladder li').length === document.querySelectorAll('.screen .panel').length"));
    check(`${pg} scope reads FIELD MANUAL`, /FIELD MANUAL/.test(await p.eval("document.querySelector('.phud-status').textContent")));
    const dups = await p.eval("(()=>{const s=new Set(),d=new Set();document.querySelectorAll('[id]').forEach(e=>s.has(e.id)?d.add(e.id):s.add(e.id));return [...d].join(',')})()");
    check(`${pg} no duplicate ids`, dups === '', dups);
    ids[pg] = await p.eval("[...document.querySelectorAll('[id]')].map(e => e.id)");
    const nCode = await p.eval("document.querySelectorAll('.fm-code').length");
    if (nCode) {
      check(`${pg} every code block has a COPY control`, await p.eval("[...document.querySelectorAll('.fm-code')].every(b => b.querySelector('button.copy'))"));
      // the clipboard itself needs a user gesture in headless Chrome, so catch what would go on it
      await p.eval("window.__copied = null; navigator.clipboard.writeText = t => { window.__copied = t; return Promise.resolve(); }; true");
      await p.eval("document.querySelector('.fm-code button.copy').click(); true"); await p.sleep(100);
      check(`${pg} COPY copies the block's exact text`, await p.eval("window.__copied === document.querySelector('.fm-code pre code').textContent"));
      check(`${pg} COPY confirms`, await p.eval("document.querySelector('.fm-code button.copy').textContent") === 'COPIED');
    }
  }
  // every link inside the manual lands on a page that exists and, with a #fragment, on a real id
  const bad = [];
  for (const pg of PAGES) {
    await p.goto(pg, 400);
    const hrefs = await p.eval("[...document.querySelectorAll('.screen a[href], .strip a[href]')].map(a => a.getAttribute('href')).filter(h => !/^(https?:|mailto:)/.test(h))");
    for (const h of hrefs) {
      const [file, frag] = h.split('#'), target = file || pg;
      if (!fs.existsSync(path.join(SITE, target))) { bad.push(pg + ' -> ' + h); continue; }
      if (frag && ids[target] && !ids[target].includes(frag)) bad.push(pg + ' -> ' + h);
    }
  }
  check('manual links all resolve', bad.length === 0, bad.slice(0, 8).join(' | '));
  await p.goto('manual.html', 900);
  const vols = await p.eval("[...document.querySelectorAll('.fm-vol a.fm-open')].map(a => a.getAttribute('href'))");
  check('library lists every source', vols.length === SOURCES.length && SOURCES.every(s => vols.includes(`manual-${s}.html`)), vols.join(','));
  // the guide's PDF links manual-N.html#c-K: the stub forwards and keeps the fragment
  await p.goto('manual-4.html#c-12', 1200);
  check('stub keeps the fragment', /manual-claude-4\.html$/.test(await p.eval('location.pathname')) && await p.eval('location.hash') === '#c-12');
  // ---- one strip on every sub-page: cockpit, PILOT, MISSIONS, HANGAR and a FIELD MANUAL dropdown ----
  // (its skeleton, ignoring which item is current and a manual's own parts row, is the same everywhere)
  const skeleton = "(() => { const n = document.querySelector('nav.strip').cloneNode(true); n.querySelectorAll('.strip-sub').forEach(e => e.remove());" +
    " n.querySelectorAll('[aria-current]').forEach(e => e.removeAttribute('aria-current')); n.querySelectorAll('.is-here').forEach(e => { e.classList.remove('is-here'); if (!e.className) e.removeAttribute('class'); });" +
    " n.querySelectorAll('details').forEach(d => d.removeAttribute('open')); return n.outerHTML.replace(/\\s+/g, ' '); })()";
  const shapes = {};
  for (const pg of ['pilot.html', 'missions.html', 'hangar.html', 'manual.html', 'manual-claude.html', 'manual-claude-3.html']) {
    await p.goto(pg, 700);
    shapes[pg] = await p.eval(skeleton);
    check(`${pg} strip reaches every page`, await p.eval("['index.html', 'pilot.html', 'missions.html', 'hangar.html', 'manual.html'].every(h => document.querySelector(`nav.strip a[href=\"${h}\"]`))"
      + ` && ${JSON.stringify(SOURCES)}.every(s => document.querySelector('nav.strip details a[href=\"manual-' + s + '.html\"]'))`));
  }
  check('the strip is the same on every sub-page', new Set(Object.values(shapes)).size === 1, Object.keys(shapes).join(','));
  // the dropdown: opens on its summary, Esc closes it (and stays on the page), a click outside closes it
  await p.goto('manual-claude-3.html', 900);
  await p.eval("document.querySelector('.strip-menu summary').click(); true");
  check('FIELD MANUAL dropdown opens', await p.eval("document.querySelector('.strip-menu details').open"));
  await p.key('Escape', 'Escape', 27); await p.sleep(600);
  check('Esc closes the dropdown first', !(await p.eval("document.querySelector('.strip-menu details').open")) && /manual-claude-3\.html$/.test(await p.eval('location.pathname')));
  await p.eval("document.querySelector('.strip-menu summary').click(); document.querySelector('main').click(); true");
  check('a click outside closes it', !(await p.eval("document.querySelector('.strip-menu details').open")));
  // every move between the manual pages takes the shutters (the insignia on the closed glass), #section links too
  for (const [from, sel] of [['manual-claude-1.html', '.strip-sub a[href="manual-claude-2.html"]'], ['manual-claude.html', 'a[href^="manual-claude-4.html#sec-"]'], ['manual.html', '.fm-open']]) {
    await p.goto(from, 900);
    await p.eval(`document.querySelector('${sel}').click(); true`); await p.sleep(250);
    check(`${from}: ${sel} takes the shutters`, await p.eval("!!document.getElementById('link') && /FIELD MANUAL/.test(document.querySelector('#link .link-label').textContent)"));
    await p.sleep(1200);
  }
  check('no JS errors on manual pages', p.errors.length === 0, p.errors.join(' | '));
  p.close();

})();
