/* hangar.js: the RX-124 TR-6 [WOUNDWORT] itself, drawn from the owner's own mesh
   (js/suitmesh.js, generated by tools/gen_dmgmap.py). WebGL2, orthographic, flat-shaded in the
   hangar's blueprint palette with the mesh's crease edges drawn over it.
   It turns on its own (not under reduced motion); drag or the arrow keys turn it; FRONT / SIDE /
   REAR swing to those views. The rifle reaches nearly three times as far as the body, so the camera
   reframes as it turns (a fit per degree, worked out once) rather than shrinking the suit to fit
   the rifle's whole sweep. */
(function () {
  'use strict';
  var S = window.BUNNYS_SUIT, canvas = document.getElementById('suit');
  if (!S || !canvas) return;
  var gl = canvas.getContext('webgl2', { antialias: true, premultipliedAlpha: false });
  function nogl() { var no = document.querySelector('.suit-nogl'); if (no) no.hidden = false; }
  if (!gl) { nogl(); return; }
  var BUNNYS = window.BUNNYS, reduce = BUNNYS.reduce, wrap360 = BUNNYS.wrap360;
  var readout = document.querySelector('.suit-yaw');

  function buf(b64) { var s = atob(b64), a = new Uint8Array(s.length); for (var i = 0; i < s.length; i++) a[i] = s.charCodeAt(i); return a.buffer; }
  var pos = new Int16Array(buf(S.pos)), tri = new Uint16Array(buf(S.tri)), edge = new Uint16Array(buf(S.edge));
  var nv = pos.length / 3;

  // ---- framing: the rotated mesh's screen bounds at a whole degree of yaw, worked out the first
  // time the turntable reaches that degree (all 360 up front is ~3.3M transforms on arrival) ----
  var PITCH = 10 * Math.PI / 180,   /* looking down on it a little */
      cp = Math.cos(PITCH), sp = Math.sin(PITCH);
  var FIT = [];
  function fitAt(deg) {
    if (FIT[deg]) return FIT[deg];
    var th = deg * Math.PI / 180, c = Math.cos(th), s = Math.sin(th);
    var x0 = 1e9, x1 = -1e9, y0 = 1e9, y1 = -1e9;
    for (var i = 0; i < nv; i++) {
      var x = pos[i * 3] / S.q, y = pos[i * 3 + 1] / S.q, z = pos[i * 3 + 2] / S.q;
      var xr = x * c + z * s, zr = -x * s + z * c, yr = y * cp - zr * sp;
      if (xr < x0) x0 = xr; if (xr > x1) x1 = xr; if (yr < y0) y0 = yr; if (yr > y1) y1 = yr;
    }
    return (FIT[deg] = [(x0 + x1) / 2, (y0 + y1) / 2, x1 - x0, y1 - y0]);
  }

  // ---- GL ----
  // A driver can hand over a WebGL2 context and still fail to compile or link: that shows the
  // fallback notice rather than leaving a blank canvas and dead buttons.
  function shader(type, src) {
    var sh = gl.createShader(type); gl.shaderSource(sh, src); gl.compileShader(sh);
    if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) { console.warn(gl.getShaderInfoLog(sh)); return null; }
    return sh;
  }
  var vs = shader(gl.VERTEX_SHADER,
    '#version 300 es\n' +
    'in vec3 p; uniform mat3 rot; uniform float q; uniform vec2 ctr, k; out vec3 vp;\n' +
    'void main() { vp = rot * (p / q); gl_Position = vec4((vp.xy - ctr) * k, -vp.z / 80.0, 1.0); }');
  var fs = shader(gl.FRAGMENT_SHADER,
    '#version 300 es\nprecision mediump float;\n' +
    'in vec3 vp; uniform int mode; out vec4 o;\n' +
    'void main() {\n' +
    '  if (mode == 1) { o = vec4(.867, .906, .933, .42); return; }\n' +
    // flat normal from the screen-space derivatives, turned to face the viewer
    '  vec3 n = normalize(cross(dFdx(vp), dFdy(vp))); if (n.z < 0.) n = -n;\n' +
    '  float key = max(dot(n, normalize(vec3(-.45, .55, .7))), 0.);\n' +
    '  float rim = pow(1. - n.z, 3.);\n' +
    '  vec3 col = mix(vec3(.035, .06, .12), vec3(.2, .3, .5), key) + vec3(.55, 1., .76) * rim * .28;\n' +
    '  o = vec4(col, 1.);\n' +
    '}');
  if (!vs || !fs) { nogl(); return; }
  var prog = gl.createProgram();
  gl.attachShader(prog, vs); gl.attachShader(prog, fs);
  gl.linkProgram(prog);
  if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) { console.warn(gl.getProgramInfoLog(prog)); nogl(); return; }
  gl.useProgram(prog);
  var U = {}; ['rot', 'q', 'ctr', 'k', 'mode'].forEach(function (n) { U[n] = gl.getUniformLocation(prog, n); });
  gl.uniform1f(U.q, S.q);

  var vao = gl.createVertexArray(); gl.bindVertexArray(vao);
  var vb = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, vb); gl.bufferData(gl.ARRAY_BUFFER, pos, gl.STATIC_DRAW);
  var loc = gl.getAttribLocation(prog, 'p');
  gl.enableVertexAttribArray(loc); gl.vertexAttribPointer(loc, 3, gl.SHORT, false, 0, 0);
  var tb = gl.createBuffer(), eb = gl.createBuffer();
  gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, tb); gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, tri, gl.STATIC_DRAW);
  gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, eb); gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, edge, gl.STATIC_DRAW);
  gl.enable(gl.DEPTH_TEST); gl.depthFunc(gl.LEQUAL);
  gl.enable(gl.BLEND); gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);

  // ---- state ----
  var yaw = 20, lastInput = -1e9, swing = null, dragging = false;
  var fit = fitAt(yaw).slice();
  var hold = 4000;                              // how long a person's input pauses the turntable
  var SPIN = 12;                                // deg/s

  function size() {
    var dpr = Math.min(window.devicePixelRatio || 1, 1.5);   // the spec's canvas cap
    var w = Math.round(canvas.clientWidth * dpr), h = Math.round(canvas.clientHeight * dpr);
    if (canvas.width !== w || canvas.height !== h) { canvas.width = w; canvas.height = h; }
  }
  function draw() {
    size();
    var W = canvas.width, H = canvas.height;
    gl.viewport(0, 0, W, H);
    gl.clearColor(0, 0, 0, 0); gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
    var th = yaw * Math.PI / 180, c = Math.cos(th), s = Math.sin(th);
    // yaw about Y, then the fixed look-down pitch about X (column-major)
    gl.uniformMatrix3fv(U.rot, false, [c, s * sp, -s * cp, 0, cp, sp, s, -c * sp, c * cp]);
    // px per mesh unit: fill the canvas with an 8% margin on whichever axis binds
    var px = Math.min(W / (fit[2] * 1.08), H / (fit[3] * 1.08));
    gl.uniform2f(U.ctr, fit[0], fit[1]);
    gl.uniform2f(U.k, 2 * px / W, 2 * px / H);
    var at = S.triAt, ea = S.edgeAt;
    // faces, pushed back a hair so their own crease lines win the depth test
    gl.uniform1i(U.mode, 0);
    gl.enable(gl.POLYGON_OFFSET_FILL); gl.polygonOffset(1, 1);
    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, tb);
    gl.drawElements(gl.TRIANGLES, (at[8] - at[0]) * 3, gl.UNSIGNED_SHORT, at[0] * 6);
    gl.disable(gl.POLYGON_OFFSET_FILL);
    gl.uniform1i(U.mode, 1);
    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, eb);
    gl.drawElements(gl.LINES, (ea[8] - ea[0]) * 2, gl.UNSIGNED_SHORT, ea[0] * 4);
    var yawText = BUNNYS.pad(Math.round(wrap360(yaw)) % 360, 3);
    if (readout && readout.textContent !== yawText) readout.textContent = yawText;
  }

  // Draw only when the picture would change, and not at all while the model is off screen or the
  // tab is hidden: 18.5k triangles redrawn at 60-120Hz for nothing is battery.
  var onScreen = true, look = new Float64Array(8), drawn = new Float64Array(8).fill(NaN);
  new IntersectionObserver(function (es) { onScreen = es[0].isIntersecting; }).observe(canvas);
  var last = performance.now();
  function frame(now) {
    requestAnimationFrame(frame);
    var dt = Math.min(0.05, (now - last) / 1000); last = now;
    if (!onScreen || document.hidden) return;
    if (swing) {
      var p = Math.min(1, (now - swing.t0) / swing.ms), e = p < .5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2;
      yaw = swing.from + swing.by * e;
      if (p >= 1) swing = null;
    } else if (!reduce && !dragging && now - lastInput > hold) {
      yaw = wrap360(yaw + SPIN * dt);
    }
    // ease the framing toward this angle's fit, so the camera follows instead of jumping
    var f = fitAt(Math.round(wrap360(yaw)) % 360), a = reduce ? 1 : 1 - Math.pow(0.002, dt);
    for (var i = 0; i < 4; i++) fit[i] += (f[i] - fit[i]) * a;
    // what the picture depends on, compared as numbers (no per-frame strings); NaN-safe first draw
    look[0] = yaw; look[1] = fit[0]; look[2] = fit[1]; look[3] = fit[2]; look[4] = fit[3];
    look[5] = canvas.clientWidth; look[6] = canvas.clientHeight; look[7] = window.devicePixelRatio;
    for (i = 0; i < 8; i++) if (!(Math.abs(look[i] - drawn[i]) <= 1e-3)) { drawn.set(look); draw(); break; }
  }
  requestAnimationFrame(frame);

  // ---- input ----
  function touch() { lastInput = performance.now(); }
  function swingTo(target) {
    var by = BUNNYS.shortestDelta(yaw, target);
    touch();
    if (reduce) { yaw = wrap360(target); swing = null; return; }
    swing = { from: yaw, by: by, t0: performance.now(), ms: 500 + Math.abs(by) * 3 };
  }
  var dragX = 0;
  canvas.addEventListener('pointerdown', function (e) {
    dragging = true; dragX = e.clientX; swing = null; touch();
    canvas.setPointerCapture(e.pointerId);
  });
  canvas.addEventListener('pointermove', function (e) {
    if (!dragging) return;
    yaw = wrap360(yaw - (e.clientX - dragX) * 0.45); dragX = e.clientX; touch();
  });
  ['pointerup', 'pointercancel'].forEach(function (t) { canvas.addEventListener(t, function () { dragging = false; touch(); }); });
  // keys work page-wide, not only with the model focused: arrows turn it, and F / S / R press the
  // view button that carries that key (the angles live once, on the buttons)
  document.addEventListener('keydown', function (e) {
    if (!BUNNYS.keyable(e)) return;
    if (e.key === 'ArrowLeft') { e.preventDefault(); swingTo(yaw + 30); return; }
    if (e.key === 'ArrowRight') { e.preventDefault(); swingTo(yaw - 30); return; }
    var vb = !e.repeat && /^[a-z]$/i.test(e.key) && document.querySelector('button[data-view][aria-keyshortcuts="' + e.key.toUpperCase() + '"]');
    if (vb) { e.preventDefault(); vb.click(); }
  });
  Array.prototype.forEach.call(document.querySelectorAll('button[data-view]'), function (b) {
    b.addEventListener('click', function () { swingTo(parseFloat(b.dataset.view) || 0); });
  });
})();
