/* generated by tools/gen_manual.py: what Ctrl+K (js/palette.js) can find */
window.BUNNYS_INDEX = [
{
"t": "Cockpit",
"h": "index.html",
"s": "HOME"
},
{
"t": "Pilot",
"h": "pilot.html",
"s": "SYLAS LYU"
},
{
"t": "Missions",
"h": "missions.html",
"s": "MISSION LOG"
},
{
"t": "Hangar",
"h": "hangar.html",
"s": "RX-124 TR-6 [WOUNDWORT]"
},
{
"t": "Unknown",
"h": "unknown.html",
"s": "OPEN CHANNEL"
},
{
"t": "Résumé",
"h": "resume.html",
"s": "PLAIN VIEW"
},
{
"t": "Field manuals",
"h": "manual.html",
"s": "LIBRARY"
},
{
"t": "Claude agents, tools and workflow",
"h": "manual-claude.html",
"s": "FM-01"
},
{
"t": "How to use this guide",
"h": "manual-claude.html#sec-1",
"s": "FM-01 · SECTION 01"
},
{
"t": "Mental model and core vocabulary",
"h": "manual-claude-1.html#sec-2",
"s": "FM-01 · SECTION 02"
},
{
"t": "The surfaces: where Claude runs",
"h": "manual-claude-1.html#sec-3",
"s": "FM-01 · SECTION 03"
},
{
"t": "Terminal and CLI basics on Windows",
"h": "manual-claude-2.html#sec-4",
"s": "FM-01 · SECTION 04"
},
{
"t": "JSON basics",
"h": "manual-claude-2.html#sec-5",
"s": "FM-01 · SECTION 05"
},
{
"t": "claude.ai features",
"h": "manual-claude-3.html#sec-6",
"s": "FM-01 · SECTION 06"
},
{
"t": "Connectors in claude.ai",
"h": "manual-claude-3.html#sec-7",
"s": "FM-01 · SECTION 07"
},
{
"t": "Skills",
"h": "manual-claude-3.html#sec-8",
"s": "FM-01 · SECTION 08"
},
{
"t": "Installing Claude Code on Windows",
"h": "manual-claude-4.html#sec-9",
"s": "FM-01 · SECTION 09"
},
{
"t": "Claude Code essentials",
"h": "manual-claude-4.html#sec-10",
"s": "FM-01 · SECTION 10"
},
{
"t": "MCP in depth",
"h": "manual-claude-4.html#sec-11",
"s": "FM-01 · SECTION 11"
},
{
"t": "Subagents",
"h": "manual-claude-4.html#sec-12",
"s": "FM-01 · SECTION 12"
},
{
"t": "Hooks",
"h": "manual-claude-4.html#sec-13",
"s": "FM-01 · SECTION 13"
},
{
"t": "Plugins and marketplaces",
"h": "manual-claude-4.html#sec-14",
"s": "FM-01 · SECTION 14"
},
{
"t": "Automation and headless use",
"h": "manual-claude-4.html#sec-15",
"s": "FM-01 · SECTION 15"
},
{
"t": "Workflow playbook",
"h": "manual-claude-5.html#sec-16",
"s": "FM-01 · SECTION 16"
},
{
"t": "Safety, privacy, cost and context hygiene",
"h": "manual-claude-5.html#sec-17",
"s": "FM-01 · SECTION 17"
},
{
"t": "Troubleshooting",
"h": "manual-claude-5.html#sec-18",
"s": "FM-01 · SECTION 18"
},
{
"t": "Four-week learning plan",
"h": "manual-claude-5.html#sec-19",
"s": "FM-01 · SECTION 19"
},
{
"t": "Quick reference",
"h": "manual-claude-5.html#sec-20",
"s": "FM-01 · SECTION 20"
},
{
"t": "Sources",
"h": "manual-claude-6.html#sec-21",
"s": "FM-01 · SECTION 21"
},
{
"t": "Consectetur adipiscing",
"h": "manual-consectetur.html",
"s": "FM-02"
},
{
"t": "Lorem ipsum",
"h": "manual-consectetur.html#sec-1",
"s": "FM-02 · SECTION 01"
},
{
"t": "Dolor sit amet",
"h": "manual-consectetur-1.html#sec-2",
"s": "FM-02 · SECTION 02"
},
{
"t": "Consectetur",
"h": "manual-consectetur-1.html#sec-3",
"s": "FM-02 · SECTION 03"
},
{
"t": "Adipiscing elit",
"h": "manual-consectetur-1.html#sec-4",
"s": "FM-02 · SECTION 04"
},
{
"t": "Sed do eiusmod",
"h": "manual-consectetur-2.html#sec-5",
"s": "FM-02 · SECTION 05"
},
{
"t": "Tempor incididunt",
"h": "manual-consectetur-2.html#sec-6",
"s": "FM-02 · SECTION 06"
},
{
"t": "Ut labore",
"h": "manual-consectetur-2.html#sec-7",
"s": "FM-02 · SECTION 07"
},
{
"t": "Magna aliqua",
"h": "manual-consectetur-3.html#sec-8",
"s": "FM-02 · SECTION 08"
},
{
"t": "Ut enim ad minim",
"h": "manual-consectetur-3.html#sec-9",
"s": "FM-02 · SECTION 09"
},
{
"t": "Quis nostrud",
"h": "manual-consectetur-3.html#sec-10",
"s": "FM-02 · SECTION 10"
},
{
"t": "Ullamco laboris",
"h": "manual-consectetur-4.html#sec-11",
"s": "FM-02 · SECTION 11"
},
{
"t": "Nisi ut aliquip",
"h": "manual-consectetur-4.html#sec-12",
"s": "FM-02 · SECTION 12"
},
{
"t": "Dolor sit amet",
"h": "manual-dolor-sit.html",
"s": "FM-03"
},
{
"t": "Lorem ipsum",
"h": "manual-dolor-sit.html#sec-1",
"s": "FM-03 · SECTION 01"
},
{
"t": "Dolor sit amet",
"h": "manual-dolor-sit-1.html#sec-2",
"s": "FM-03 · SECTION 02"
},
{
"t": "Consectetur",
"h": "manual-dolor-sit-1.html#sec-3",
"s": "FM-03 · SECTION 03"
},
{
"t": "Adipiscing elit",
"h": "manual-dolor-sit-2.html#sec-4",
"s": "FM-03 · SECTION 04"
},
{
"t": "Sed do eiusmod",
"h": "manual-dolor-sit-2.html#sec-5",
"s": "FM-03 · SECTION 05"
},
{
"t": "Lorem ipsum dolor",
"h": "manual-lorem-ipsum.html",
"s": "FM-04"
},
{
"t": "Lorem ipsum",
"h": "manual-lorem-ipsum.html#sec-1",
"s": "FM-04 · SECTION 01"
},
{
"t": "Dolor sit amet",
"h": "manual-lorem-ipsum-1.html#sec-2",
"s": "FM-04 · SECTION 02"
},
{
"t": "Consectetur",
"h": "manual-lorem-ipsum-1.html#sec-3",
"s": "FM-04 · SECTION 03"
},
{
"t": "Adipiscing elit",
"h": "manual-lorem-ipsum-1.html#sec-4",
"s": "FM-04 · SECTION 04"
},
{
"t": "Sed do eiusmod",
"h": "manual-lorem-ipsum-2.html#sec-5",
"s": "FM-04 · SECTION 05"
},
{
"t": "Tempor incididunt",
"h": "manual-lorem-ipsum-2.html#sec-6",
"s": "FM-04 · SECTION 06"
},
{
"t": "Ut labore",
"h": "manual-lorem-ipsum-2.html#sec-7",
"s": "FM-04 · SECTION 07"
},
{
"t": "Magna aliqua",
"h": "manual-lorem-ipsum-3.html#sec-8",
"s": "FM-04 · SECTION 08"
},
{
"t": "Ut enim ad minim",
"h": "manual-lorem-ipsum-3.html#sec-9",
"s": "FM-04 · SECTION 09"
},
{
"t": "Magna aliqua",
"h": "manual-magna-aliqua.html",
"s": "FM-05"
},
{
"t": "Lorem ipsum",
"h": "manual-magna-aliqua.html#sec-1",
"s": "FM-05 · SECTION 01"
},
{
"t": "Dolor sit amet",
"h": "manual-magna-aliqua-1.html#sec-2",
"s": "FM-05 · SECTION 02"
},
{
"t": "Consectetur",
"h": "manual-magna-aliqua-1.html#sec-3",
"s": "FM-05 · SECTION 03"
},
{
"t": "Adipiscing elit",
"h": "manual-magna-aliqua-1.html#sec-4",
"s": "FM-05 · SECTION 04"
},
{
"t": "Sed do eiusmod",
"h": "manual-magna-aliqua-2.html#sec-5",
"s": "FM-05 · SECTION 05"
},
{
"t": "Tempor incididunt",
"h": "manual-magna-aliqua-2.html#sec-6",
"s": "FM-05 · SECTION 06"
},
{
"t": "Ut labore",
"h": "manual-magna-aliqua-2.html#sec-7",
"s": "FM-05 · SECTION 07"
},
{
"t": "Tempor incididunt",
"h": "manual-tempor.html",
"s": "FM-06"
},
{
"t": "Lorem ipsum",
"h": "manual-tempor.html#sec-1",
"s": "FM-06 · SECTION 01"
},
{
"t": "Dolor sit amet",
"h": "manual-tempor-1.html#sec-2",
"s": "FM-06 · SECTION 02"
},
{
"t": "Consectetur",
"h": "manual-tempor-2.html#sec-3",
"s": "FM-06 · SECTION 03"
},
{
"t": "Adipiscing elit",
"h": "manual-tempor-3.html#sec-4",
"s": "FM-06 · SECTION 04"
}
];
