"""Trace the enemy suit from the supplied reference PNG into SVG paths.

Real edge tracing, not a redraw: segment the image into tone bands, walk the
boundary of each region (Moore-neighbour), simplify with Douglas-Peucker, then
map into panorama units. Output is written as a Python literal that gen_pano.py
imports, so the panorama build stays a single deterministic step.
"""
import io, json, os, sys
import numpy as np
from PIL import Image
from scipy import ndimage

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tracelib import trace_components, rdp   # noqa: E402  (shared with gen_dmgmap.py)

REF = os.environ.get('REF', r'C:\Users\thirt\AppData\Local\Temp\claude\c--Users-thirt-Desktop-testing-neocities\9e76d4e0-fd71-4f49-a6af-827c6977e850\images\5.png')
OUT = os.path.join(os.path.dirname(__file__), 'suit_trace.py')

im = Image.open(REF).convert('RGB')
a = np.asarray(im).astype(float)
lum = a.mean(2)
H, W = lum.shape

# The suit is the dark mass in the middle; the fog behind it is lighter and bluer.
# Blue-dominance separates them better than luminance alone, because the suit's
# rim-lit edges are bright but stay neutral while the fog stays blue.
# reference 5 is the suit in black on a white sweep, so plain luminance separates it
body = lum < 205

body = ndimage.binary_closing(body, np.ones((5, 5)))
body = ndimage.binary_fill_holes(body)
# thicken thin features (the head spike is only a few px wide) so the smoothing
# pass below cannot erase them, then smooth the staircase off the contour
body = ndimage.binary_dilation(body, np.ones((3, 3)))
body = ndimage.median_filter(body, size=7)
body = ndimage.binary_fill_holes(body)
lab, n = ndimage.label(body)
if n:
    sizes = ndimage.sum(body, lab, range(1, n + 1))
    body = lab == (int(np.argmax(sizes)) + 1)
body = ndimage.binary_fill_holes(body)

ys, xs = np.where(body)
print('mask bbox x %d..%d  y %d..%d  fill %.1f%%' % (xs.min(), xs.max(), ys.min(), ys.max(), 100.0 * body.mean()))

if '--preview' in sys.argv:
    prev = np.zeros((H, W, 3), np.uint8)
    prev[..., 1] = (body * 200).astype(np.uint8)
    prev[..., 0] = np.clip(lum, 0, 255).astype(np.uint8)
    Image.fromarray(prev).resize((W // 2, H // 2)).save(os.path.join(os.path.dirname(__file__), '..', 'tests', 'out', 'trace-mask.png'))
    print('wrote tests/out/trace-mask.png')

# ---------------------------------------------------------------- contour tracing
# ---------------------------------------------------------------- tone bands -> paths
# Three layers read as a lit mechanical shape at small size: the silhouette, the
# mid-tone armour that catches the sky, and the bright rim highlights.
inside = body
mid = inside & (lum > 88) & (lum <= 150)
lit = inside & (lum > 150)
mid = ndimage.binary_opening(mid, np.ones((3, 3)))
lit = ndimage.binary_opening(lit, np.ones((2, 2)))

# the mono-eye: the strongly orange pixels
eye = (a[:, :, 0] > 110) & (a[:, :, 0] - a[:, :, 2] > 40)

# map image pixels into panorama units: keep the aspect, put the feet on y=0,
# centre on x=0, and scale so the whole suit stands TALL units high.
TALL = 690.0   # scaled at render time by SS
x0, x1 = xs.min(), xs.max()
y0, y1 = ys.min(), ys.max()
s = TALL / (y1 - y0)
cxp = (x0 + x1) / 2.0


def to_units(p):
    return np.stack([(p[:, 0] - cxp) * s, (p[:, 1] - y1) * s], 1)


def paths(mask, eps, min_area=140):
    d = []
    for c in trace_components(mask, min_area):
        c = rdp(c, eps)
        if len(c) < 4:
            continue
        q = to_units(c)
        d.append('M' + 'L'.join('%.1f %.1f' % (x, y) for x, y in q) + 'Z')
    return ''.join(d)


LAYERS = {
    'body': paths(inside, 2.2, 400),
    'mid': paths(mid, 2.6, 420),
    'lit': paths(lit, 2.4, 300),
    'eye': paths(eye, 1.2, 20),
}
eyec = np.argwhere(eye)
EYE_XY = (float((eyec[:, 1].mean() - cxp) * s), float((eyec[:, 0].mean() - y1) * s)) if len(eyec) else (0.0, -TALL * 0.845)

with io.open(OUT, 'w', encoding='utf-8') as fh:
    fh.write('# Generated by trace_suit.py from the supplied reference. Do not hand-edit.\n')
    fh.write('# Panorama units: feet on y=0, centred on x=0, %.0f units tall.\n' % TALL)
    fh.write('EYE_POS = %r\n' % (EYE_XY,))   # distinct from the EYE path written below
    for k, v in LAYERS.items():
        fh.write('%s = %r\n' % (k.upper(), v))
print('layers:', {k: (len(v), v.count('M')) for k, v in LAYERS.items()}, 'eye at', EYE_XY)
print('wrote', OUT, os.path.getsize(OUT) // 1024, 'KB')
